"""Pelican configuration. Keep this minimal — see PLAN.md."""

import os
import time
from glob import glob as _glob

# Changes every build; appended as ?v=… to CSS links so browsers never serve
# a stale stylesheet against freshly-changed markup (see base.html).
CACHE_BUST = int(time.time())


def _gallery_images():
    """List image filenames in content/images/gallery/, sorted.

    Exposed to templates via JINJA_GLOBALS so gallery.html can glob the
    folder at build time without a plugin (see PLAN.md "Gallery").
    """
    base = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "content", "images", "gallery",
    )
    exts = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg")
    names = (os.path.basename(p) for p in _glob(os.path.join(base, "*")))
    return sorted(n for n in names if n.lower().endswith(exts))


AUTHOR = "Kenjiro"
SITENAME = "kenjiro's botanical garden"
SITEURL = ""  # empty for local dev; set per-environment at publish time

# --- Paths -------------------------------------------------------------------
PATH = "content"            # where the source content lives
OUTPUT_PATH = "output"      # generated build artifact (gitignored)
THEME = "themes/mytheme"

ARTICLE_PATHS = ["blog"]            # Markdown posts → article.html
PAGE_PATHS = ["pages"]              # Markdown pages → page.html
STATIC_PATHS = ["images", "projects", "music"]  # copied VERBATIM, no templating

TIMEZONE = "America/New_York"
DEFAULT_LANG = "en"
DEFAULT_DATE_FORMAT = "%Y-%m-%d"

# --- Turn off machinery we don't want ---------------------------------------
# No feeds during local development.
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# No pagination yet — one flat index.
DEFAULT_PAGINATION = False

# "index" → the home page (the Winamp clone). "blog" → the post-listing
# page at /blog/ (its template gets the global `articles` context).
DIRECT_TEMPLATES = ["index", "blog"]
BLOG_SAVE_AS = "blog/index.html"
BLOG_URL = "blog/"
AUTHOR_SAVE_AS = ""
AUTHORS_SAVE_AS = ""
CATEGORY_SAVE_AS = ""
CATEGORIES_SAVE_AS = ""
TAG_SAVE_AS = ""
TAGS_SAVE_AS = ""
ARCHIVES_SAVE_AS = ""

# Clean-ish URLs for articles: /blog/<slug>/
ARTICLE_URL = "blog/{slug}/"
ARTICLE_SAVE_AS = "blog/{slug}/index.html"
PAGE_URL = "{slug}/"
PAGE_SAVE_AS = "{slug}/index.html"

# Relative URLs make the local --listen preview work without SITEURL.
RELATIVE_URLS = True

# Expose the gallery glob to templates (see gallery.html).
JINJA_GLOBALS = {"gallery_images": _gallery_images, "cache_bust": CACHE_BUST}

# --- Skins (see SKIN_IMPORT.md) ---------------------------------------------
# Skins are generated by import_skin.py into themes/mytheme/static/skins/<name>/.
# Set ACTIVE_SKIN to a folder name to re-skin the whole site; leave it "" to use
# the theme's built-in "aero" palette. base.html links the skin's CSS when set,
# and the `skintext` filter renders headings in the skin's bitmap font.
ACTIVE_SKIN = "blame-wired"  # e.g. "necromech" or "blame-wired"; "" = built-in aero


def _skintext_filter():
    """Build the `skintext` Jinja filter: turn a string into a row of bitmap-
    font glyph spans, using the active skin's chars.json offsets into text.png.

    Falls back to returning the plain string unchanged when no skin is active
    or the skin has no bitmap font, so templates never break.
    """
    import json
    from markupsafe import Markup, escape

    chars = None
    if ACTIVE_SKIN:
        cj = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "themes", "mytheme", "static", "skins", ACTIVE_SKIN, "chars.json",
        )
        if os.path.isfile(cj):
            with open(cj, encoding="utf-8") as fh:
                chars = json.load(fh)

    def skintext(text):
        text = "" if text is None else str(text)
        if not chars:
            return escape(text)  # no bitmap font available; render as plain text
        spans = []
        for ch in text.upper():
            pos = chars.get(ch) or chars.get(" ")
            if pos is None:
                continue
            x = "0" if pos[0] == 0 else "-%dpx" % pos[0]
            y = "0" if pos[1] == 0 else "-%dpx" % pos[1]
            spans.append(
                "<span class=\"skinchar\" style=\"background-position:%s %s\"></span>" % (x, y)
            )
        return Markup("<span class=\"skintext\" role=\"img\" aria-label=\"%s\">%s</span>"
                      % (escape(text), "".join(spans)))

    return skintext


JINJA_FILTERS = {"skintext": _skintext_filter()}


# --- Homepage audio player: music manifest (see PLAYER.md) -------------------
# content/music/ is copied verbatim (STATIC_PATHS). After each build we scan it
# and write output/music.json — the ordered track list the player fetches. The
# directory is the source of truth: drop in an audio file, rebuild, it appears.
_AUDIO_EXTS = (".mp3", ".ogg", ".oga", ".m4a", ".opus", ".aac", ".flac", ".wav")


def _title_from_filename(name):
    """Readable title from a filename stem: drop a leading "NN " or "NN_" track
    number, swap _/- for spaces, collapse whitespace."""
    import re
    stem = os.path.splitext(name)[0]
    stem = re.sub(r"^\s*\d+\s*[-_.]\s*", "", stem)  # strip leading "01 - "
    stem = re.sub(r"[_-]+", " ", stem).strip()
    return re.sub(r"\s+", " ", stem) or os.path.splitext(name)[0]


def _fmt_len(seconds):
    """Seconds -> "m:ss" (Webamp-style); "" if unknown."""
    if not seconds or seconds <= 0:
        return ""
    s = int(round(seconds))
    return "%d:%02d" % (s // 60, s % 60)


def _track_meta(path, name):
    """(title, artist, length) for one audio file. Pulls title/artist/length
    from ID3/Vorbis tags via mutagen when available; falls back to the filename
    for the title (artist/length stay empty). Tags are optional (PLAYER.md)."""
    title = artist = None
    length = None
    try:
        import mutagen
        mf = mutagen.File(path, easy=True)
        if mf is not None:
            if mf.tags:
                title = (mf.tags.get("title") or [None])[0]
                artist = (mf.tags.get("artist") or [None])[0]
            if mf.info:
                length = mf.info.length
    except Exception:
        pass  # no mutagen, or unreadable tags — fall back to the filename
    return (title or _title_from_filename(name)), (artist or ""), _fmt_len(length)


def _write_music_manifest(pelican):
    """`finalized` signal handler: scan content/music/ and emit music.json.
    The directory is the source of truth (drop a file in, rebuild, it appears);
    metadata comes from the file's tags — do NOT hand-edit music.json."""
    import json
    src = os.path.join(pelican.settings["PATH"], "music")
    out = pelican.settings["OUTPUT_PATH"]
    tracks = []
    if os.path.isdir(src):
        for name in sorted(os.listdir(src)):
            if name.lower().endswith(_AUDIO_EXTS):
                title, artist, length = _track_meta(os.path.join(src, name), name)
                tracks.append({"file": "music/" + name, "title": title,
                               "artist": artist, "length": length})
    with open(os.path.join(out, "music.json"), "w", encoding="utf-8") as fh:
        json.dump(tracks, fh, ensure_ascii=False, indent=2)
    print("  [music] %d track(s) -> music.json" % len(tracks))


# Wire the hook at config-load time (Pelican executes this file at startup).
from pelican import signals as _signals  # noqa: E402
_signals.finalized.connect(_write_music_manifest)
